# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 21:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('label', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='RiskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.CommunitySystem')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.Indicator')),
                ('regions', models.ManyToManyField(related_name='risk', to='planit_data.GeoRegion')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='risktemplate',
            name='weather_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.WeatherEvent'),
        ),
    ]
