# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planit_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('community_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.CommunitySystem')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.Indicator')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.UserLocation')),
                ('weather_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.WeatherEvent')),
            ],
        ),
    ]
