# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0002_move_user_risk_user_location_to_planitdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='georegion',
            name='name',
            field=models.CharField(default='Migrated', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlocation',
            name='name',
            field=models.CharField(default='Migrated', max_length=256),
            preserve_default=False,
        ),
    ]
