# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planit_data', '0004_concern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrisk',
            name='location',
        ),
        migrations.AddField(
            model_name='userrisk',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
