# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0006_apitoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risktemplate',
            name='community_system',
        ),
        migrations.AddField(
            model_name='risktemplate',
            name='community_system',
            field=models.ManyToManyField(blank=True, related_name='risk', to='planit_data.CommunitySystem'),
        ),
        migrations.RemoveField(
            model_name='risktemplate',
            name='indicator',
        ),
        migrations.AddField(
            model_name='risktemplate',
            name='indicator',
            field=models.ManyToManyField(blank=True, related_name='climate_risk', to='planit_data.Indicator'),
        ),
    ]
