# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0007_delete_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalRiskRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('georegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.GeoRegion')),
                ('prior_ranked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prior_ranked_event', to='planit_data.WeatherEvent')),
                ('weather_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.WeatherEvent')),
            ],
        ),
        migrations.RemoveField(
            model_name='risktemplate',
            name='community_system',
        ),
        migrations.AddField(
            model_name='risktemplate',
            name='community_system',
            field=models.ManyToManyField(blank=True, related_name='risk', to='planit_data.CommunitySystem'),
        ),
        migrations.RemoveField(
            model_name='risktemplate',
            name='indicator',
        ),
        migrations.AddField(
            model_name='risktemplate',
            name='indicator',
            field=models.ManyToManyField(blank=True, related_name='climate_risk', to='planit_data.Indicator'),
        ),
        migrations.AlterUniqueTogether(
            name='regionalriskrank',
            unique_together=set([('georegion', 'prior_ranked_event'), ('georegion', 'weather_event')]),
        ),
    ]
