# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0008_change_risktemplate_fieldtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalRiskRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('georegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.GeoRegion')),
                ('next_ranked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_ranked_event', to='planit_data.WeatherEvent')),
                ('weather_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.WeatherEvent')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='regionalriskrank',
            unique_together=set([('georegion', 'next_ranked_event'), ('georegion', 'weather_event')]),
        ),
    ]
