# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0008_modify_risktemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalRiskRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('georegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.GeoRegion')),
                ('weather_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.WeatherEvent')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='regionalriskrank',
            unique_together=set([('georegion', 'weather_event'), ('georegion', 'order')]),
        ),
        migrations.AlterModelOptions(
            name='regionalriskrank',
            options={'ordering': ['georegion', 'order']},
        ),
    ]
