# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0009_regionalriskrank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrisk',
            name='community_system',
        ),
        migrations.RemoveField(
            model_name='userrisk',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='userrisk',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrisk',
            name='weather_event',
        ),
        migrations.DeleteModel(
            name='UserRisk',
        ),
    ]
