# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0010_auto_20171117_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegionalRiskRank',
            new_name='WeatherEventRank',
        ),
    ]
