# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0011_auto_20171117_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concern',
            old_name='tagline',
            new_name='tagline_positive',
        ),
        migrations.AddField(
            model_name='concern',
            name='tagline_negative',
            field=models.CharField(default='less', max_length=256),
            preserve_default=False,
        ),
    ]
