# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0011_auto_20171117_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='indicator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planit_data.Indicator'),
        ),
    ]
