# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0011_auto_20171117_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherevent',
            name='concern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planit_data.Concern'),
        ),
    ]
