# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0011_auto_20171117_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherevent',
            name='coastal_only',
            field=models.BooleanField(default=False),
        ),
    ]
