# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0012_weatherevent_coastal_only'),
        ('planit_data', '0012_auto_20171129_1658'),
    ]

    operations = [
    ]
