# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0012_auto_20171128_1631'),
        ('planit_data', '0012_weatherevent_concern'),
    ]

    operations = [
    ]
