# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0012_auto_20171128_1631'),
        ('planit_data', '0012_weatherevent_concern'),
        ('planit_data', '0013_merge_20171201_1438'),
    ]

    operations = [
    ]
