# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0014_merge_20171201_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('community_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.CommunitySystem')),
            ],
            options={
                'ordering': ['weather_event', 'order'],
            },
        ),
        migrations.RemoveField(
            model_name='risktemplate',
            name='community_system',
        ),
        migrations.RemoveField(
            model_name='risktemplate',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='risktemplate',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='risktemplate',
            name='weather_event',
        ),
        migrations.AddField(
            model_name='weatherevent',
            name='indicators',
            field=models.ManyToManyField(blank=True, related_name='weather_events', to='planit_data.Indicator'),
        ),
        migrations.DeleteModel(
            name='RiskTemplate',
        ),
        migrations.AddField(
            model_name='defaultrisk',
            name='weather_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.WeatherEvent'),
        ),
        migrations.AddField(
            model_name='weatherevent',
            name='community_systems',
            field=models.ManyToManyField(through='planit_data.DefaultRisk', to='planit_data.CommunitySystem'),
        ),
        migrations.AlterUniqueTogether(
            name='defaultrisk',
            unique_together=set([('weather_event', 'order'), ('weather_event', 'community_system')]),
        ),
    ]
