# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0015_auto_20171212_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherevent',
            name='display_class',
            field=models.CharField(choices=[('precipitation', 'Precipitation'), ('heat', 'Heat'), ('extreme-events', 'Extreme Events')], default='heat', max_length=32),
            preserve_default=False,
        ),
    ]
