# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 19:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20171211_1726'),
        ('planit_data', '0016_weatherevent_display_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('probability', models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('low', 'Low'), ('mod low', 'Moderately low'), ('moderate', 'Moderate'), ('mod high', 'Moderately high'), ('high', 'High')], max_length=16)),
                ('frequency', models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('decreasing', 'Decreasing'), ('no change', 'No change'), ('increasing', 'Increasing')], max_length=16)),
                ('intensity', models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('decreasing', 'Decreasing'), ('no change', 'No change'), ('increasing', 'Increasing')], max_length=16)),
                ('impact_magnitude', models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('low', 'Low'), ('mod low', 'Moderately low'), ('moderate', 'Moderate'), ('mod high', 'Moderately high'), ('high', 'High')], max_length=16)),
                ('impact_description', models.TextField(blank=True)),
                ('adaptive_capacity', models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('low', 'Low'), ('mod low', 'Moderately low'), ('moderate', 'Moderate'), ('mod high', 'Moderately high'), ('high', 'High')], max_length=16)),
                ('related_adaptive_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, size=None)),
                ('adaptive_capacity_description', models.TextField(blank=True)),
                ('community_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.CommunitySystem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PlanItOrganization')),
                ('weather_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.WeatherEvent')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='organizationrisk',
            unique_together=set([('weather_event', 'community_system', 'organization')]),
        ),
    ]
