# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 21:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0018_relatedadaptivevalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrisk',
            name='adaptive_capacity',
            field=models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('low', 'Low'), ('mod low', 'Moderately low'), ('moderate', 'Moderate'), ('mod high', 'Moderately high'), ('high', 'High')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='organizationrisk',
            name='adaptive_capacity_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationrisk',
            name='frequency',
            field=models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('decreasing', 'Decreasing'), ('no change', 'No change'), ('increasing', 'Increasing')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='organizationrisk',
            name='impact_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationrisk',
            name='impact_magnitude',
            field=models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('low', 'Low'), ('mod low', 'Moderately low'), ('moderate', 'Moderate'), ('mod high', 'Moderately high'), ('high', 'High')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='organizationrisk',
            name='intensity',
            field=models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('decreasing', 'Decreasing'), ('no change', 'No change'), ('increasing', 'Increasing')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='organizationrisk',
            name='probability',
            field=models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('low', 'Low'), ('mod low', 'Moderately low'), ('moderate', 'Moderate'), ('mod high', 'Moderately high'), ('high', 'High')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='organizationrisk',
            name='related_adaptive_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, null=True, size=None),
        ),
    ]
