# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 15:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('action_steps', '0004_order_by_name'),
        ('planit_data', '0018_relatedadaptivevalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=1024)),
                ('action_type', models.CharField(blank=True, max_length=1024)),
                ('action_goal', models.CharField(blank=True, max_length=1024)),
                ('implementation_details', models.TextField(blank=True)),
                ('visibility', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=16)),
                ('implementation_notes', models.TextField(blank=True)),
                ('improvements_adaptive_capacity', models.TextField(blank=True)),
                ('immprovements_impacts', models.TextField(blank=True)),
                ('collaborators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024), default=list, size=None)),
                ('funding', models.TextField(blank=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='organization_actions', to='action_steps.ActionCategory')),
                ('organization_risk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planit_data.OrganizationRisk')),
            ],
        ),
    ]
