# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0019_organizationaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationaction',
            old_name='action',
            new_name='name',
        )
    ]
