# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 14:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0019_organizationaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaction',
            name='action',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='organizationaction',
            name='action_goal',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='organizationaction',
            name='action_type',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='organizationaction',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='organizationaction',
            name='collaborators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='organizationaction',
            name='funding',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationaction',
            name='immprovements_impacts',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationaction',
            name='implementation_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationaction',
            name='implementation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationaction',
            name='improvements_adaptive_capacity',
            field=models.TextField(blank=True),
        ),
    ]
