# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0020_auto_rename_action_field'),
        ('planit_data', '0020_auto_20180119_2131'),
    ]

    operations = [
    ]
