# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0020_auto_rename_action_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationaction',
            old_name='immprovements_impacts',
            new_name='improvements_impacts',
        ),
    ]
