# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0024_update_org_weather_event_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationweatherevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_events', to='users.PlanItOrganization'),
        ),
    ]
