# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0025_rename_org_weather_event_related_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrisk',
            name='community_system',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='planit_data.CommunitySystem'),
        ),
        migrations.AlterField(
            model_name='organizationrisk',
            name='weather_event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='planit_data.WeatherEvent'),
        ),
    ]
