# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0026_relax_risk_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaction',
            name='organization_risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit_data.OrganizationRisk'),
        ),
    ]
