# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0027_one_to_many_risk_to_action'),
        ('planit_data', '0027_remove_weatherevent_displayclass_choices'),
    ]

    operations = [
    ]
