# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0028_merge_20180216_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultrisk',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
