# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0029_defaultrisk_order_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultrisk',
            options={'ordering': ['weather_event', 'order', 'community_system']},
        ),
    ]
