# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0033_concern_indicator_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherevent',
            name='concern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit_data.Concern'),
        ),
    ]
