# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0034_weatherevent_concern_delete_setnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='static_units',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
