# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0037_auto_20180324_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaction',
            name='visibility',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('request', 'Requested Public'), ('private', 'Private')], default='private', max_length=16),
        ),
    ]
