# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-25 19:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0038_auto_20180327_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateAssessmentRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('indicators', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('state_fips', models.CharField(max_length=2)),
                ('geoid', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('indicators', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
