# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-26 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0039_climateassessmentregion_county'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'counties'},
        ),
    ]
