# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-17 18:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0041_auto_20191017_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climateassessmentregion',
            name='indicators',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
