# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-17 23:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0042_auto_20191017_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactMapLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_type', models.CharField(choices=[('county', 'county'), ('arcgis', 'arcgis'), ('vectortile', 'vectortile')], max_length=20)),
                ('attribution', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True)),
                ('attribute', models.CharField(blank=True, max_length=256)),
                ('max_zoom', models.IntegerField(blank=True, null=True)),
                ('show_borders_at', models.IntegerField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True)),
                ('state_fips', models.CharField(blank=True, default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactMapLegendRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#([a-fA-F0-9]{3}|[a-fA-F0-9]{6})$')])),
                ('label', models.CharField(blank=True, max_length=100)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('impact_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legend', to='planit_data.ImpactMapLayer')),
            ],
        ),
        migrations.AlterModelOptions(
            name='impact',
            options={'ordering': ['label']},
        ),
        migrations.RenameField(
            model_name='impact',
            old_name='external_link',
            new_name='external_download_link',
        ),
        migrations.RenameField(
            model_name='impact',
            old_name='name',
            new_name='label',
        ),
        migrations.AddField(
            model_name='impactmaplayer',
            name='impact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planit_data.Impact'),
        ),
    ]
