# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-18 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0043_auto_20191017_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmaplayer',
            name='impact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_layer', to='planit_data.Impact'),
        ),
    ]
