# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0044_auto_20191018_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactcommunitysystemrank',
            name='impact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_system_ranks', to='planit_data.Impact'),
        ),
        migrations.AlterField(
            model_name='impactweathereventrank',
            name='impact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_event_ranks', to='planit_data.Impact'),
        ),
    ]
