# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0045_auto_20191029_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='attribute',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='impact',
            name='region',
            field=models.CharField(blank=True, choices=[('county', 'County'), ('nca', 'National Climate Assessment region')], max_length=10),
        ),
        migrations.AddField(
            model_name='impact',
            name='tagline_negative',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='impact',
            name='tagline_no_change',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='impact',
            name='tagline_positive',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
