# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-21 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0046_auto_20191030_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmaplegendrow',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
