# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-21 23:40
from itertools import groupby

from django.db import migrations


def add_order(apps, schema_editor):
    ImpactMapLegendRow = apps.get_model('planit_data', 'ImpactMapLegendRow')

    rows = ImpactMapLegendRow.objects.all().order_by('impact_layer', 'label', 'min_value')
    legends = groupby(rows, lambda row: row.impact_layer_id)
    for layer_id, legend_rows in legends:
        legend_rows = sorted(legend_rows,
                             key=lambda row: row.label if row.label else row.min_value)
        for i, legend_row in enumerate(legend_rows):
            legend_row.order = i + 1
            legend_row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0047_impactmaplegendrow_order'),
    ]

    operations = [
        migrations.RunPython(add_order, migrations.RunPython.noop)
    ]
