# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0048_add_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impactcommunitysystemrank',
            options={'ordering': ['georegion', 'community_system']},
        ),
        migrations.AlterModelOptions(
            name='impactmaplegendrow',
            options={'ordering': ['impact_layer', 'order']},
        ),
        migrations.AlterModelOptions(
            name='impactweathereventrank',
            options={'ordering': ['georegion', 'weather_event']},
        ),
        migrations.AlterField(
            model_name='impactmaplegendrow',
            name='order',
            field=models.IntegerField(),
        ),
    ]
