# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0050_impactmaplayer_legend_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmaplayer',
            name='layer_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
