# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-26 19:04
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F, Value


def set_is_modified(apps, schema_editor):
    OrganizationRisk = apps.get_model('planit_data', 'OrganizationRisk')
    (OrganizationRisk.objects
     .exclude(
         probability='', frequency='', intensity='', impact_magnitude='', impact_description='',
         adaptive_capacity='', adaptive_capacity_description='', related_adaptive_values=[]
     )
     .update(is_modified=True))

class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0052_risk_is_modified_flag'),
    ]

    operations = [
        migrations.RunPython(set_is_modified, migrations.RunPython.noop)
    ]
