# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-31 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0053_risk_is_modified_flag_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationweatherevent',
            name='frequency',
            field=models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('decreasing', 'Decreasing'), ('no change', 'No change'), ('increasing', 'Increasing')], max_length=16),
        ),
        migrations.AddField(
            model_name='organizationweatherevent',
            name='intensity',
            field=models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('decreasing', 'Decreasing'), ('no change', 'No change'), ('increasing', 'Increasing')], max_length=16),
        ),
        migrations.AddField(
            model_name='organizationweatherevent',
            name='probability',
            field=models.CharField(blank=True, choices=[('unsure', 'Unsure'), ('low', 'Low'), ('mod low', 'Moderately low'), ('moderate', 'Moderate'), ('mod high', 'Moderately high'), ('high', 'High')], max_length=16),
        ),
    ]
