# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-31 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0054_add_hazard_fields_to_org_weather_event'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE planit_data_organizationweatherevent we
            SET probability = Coalesce((
                SELECT r.probability
                FROM planit_data_organizationrisk r
                WHERE r.probability != ''
                    AND r.organization_id = we.organization_id
                    AND r.weather_event_id = we.weather_event_id
                LIMIT 1
            ), ''),
            frequency = Coalesce((
                SELECT r.frequency
                FROM planit_data_organizationrisk r
                WHERE r.frequency != ''
                    AND r.organization_id = we.organization_id
                    AND r.weather_event_id = we.weather_event_id
                LIMIT 1
            ), ''),
            intensity = Coalesce((
                SELECT r.intensity
                FROM planit_data_organizationrisk r
                WHERE r.intensity != ''
                    AND r.organization_id = we.organization_id
                    AND r.weather_event_id = we.weather_event_id
                LIMIT 1
            ), ''); 
            """,
            migrations.RunSQL.noop
        )
    ]
