# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-31 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0055_hazard_fields_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationrisk',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='organizationrisk',
            name='intensity',
        ),
        migrations.RemoveField(
            model_name='organizationrisk',
            name='probability',
        ),
    ]
