# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-31 20:58
from __future__ import unicode_literals

import compositefk.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0056_delete_hazard_fields_from_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrisk',
            name='organization_weather_event',
            field=compositefk.fields.CompositeForeignKey(default=None, null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='planit_data.OrganizationWeatherEvent', to_fields={'organization': compositefk.fields.LocalFieldValue('organization'), 'weather_event': compositefk.fields.LocalFieldValue('weather_event')}),
            preserve_default=False,
        ),
    ]
