# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-01 17:13
from __future__ import unicode_literals

from django.db import migrations


# Code from https://stackoverflow.com/a/56644496
def _make_deferrable(apps, schema_editor):
    """
    Change the unique constraint to be deferrable
    """
    # Get the db name of the constraint
    OrganizationWeatherEvent = apps.get_model('planit_data', 'OrganizationWeatherEvent')
    CONSTRAINT_NAME = schema_editor._constraint_names(OrganizationWeatherEvent,
                                                      ['organization_id', 'order'],
                                                      unique=True)[0]
    TABLE_NAME = OrganizationWeatherEvent._meta.db_table

    # Drop then re-add with deferrable as ALTER doesnt seem to work for unique constraints in psql
    with schema_editor.connection.create_cursor() as curs:
        curs.execute(
            f'ALTER TABLE {TABLE_NAME} DROP CONSTRAINT {CONSTRAINT_NAME};'
        )
        curs.execute(
            f'ALTER TABLE {TABLE_NAME} ADD CONSTRAINT'
            f' {CONSTRAINT_NAME}'
            f' UNIQUE ("organization_id", "order") DEFERRABLE INITIALLY DEFERRED;'
        )


def _unmake_deferrable(apps, schema_editor):
    """
    Reverse the unique constraint to be not deferrable
    """
    # Get the db name of unique constraint
    OrganizationWeatherEvent = apps.get_model('myapp', 'OrganizationWeatherEvent')
    CONSTRAINT_NAME = schema_editor._constraint_names(OrganizationWeatherEvent,
                                                      ['organization_id', 'order'],
                                                      unique=True)[0]
    TABLE_NAME = OrganizationWeatherEvent._meta.db_table

    with schema_editor.connection.create_cursor() as curs:
        curs.execute(
            f'ALTER TABLE {TABLE_NAME} DROP CONSTRAINT {CONSTRAINT_NAME};'
        )
        curs.execute(
            f'ALTER TABLE {TABLE_NAME} ADD CONSTRAINT'
            f' {CONSTRAINT_NAME}'
            f' UNIQUE ("organization_id", "order") NOT DEFERRABLE;'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0057_add_virtual_field_to_risk'),
    ]

    operations = [
        migrations.RunPython(code=_make_deferrable, reverse_code=_unmake_deferrable)
    ]
