# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 18:43
from __future__ import unicode_literals

from django.db import migrations

HOST_NAME = 'localhost:8100'


def insert_sites(apps, schema_editor):
        """Populate the sites model"""
        Site = apps.get_model('sites', 'Site')
        Site.objects.all().delete()
        Site.objects.create(domain=HOST_NAME, name=HOST_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_sites, migrations.RunPython.noop)
    ]
