from rest_framework.viewsets import ReadOnlyModelViewSet
from rest_framework.response import Response

from planit_data.models import Concern
from planit_data.serializers import ConcernSerializer


class ConcernViewSet(ReadOnlyModelViewSet):
    """Filter out the dummy scenario generated by migrations as a placeholder for older data."""

    queryset = Concern.objects.all()
    serializer_class = ConcernSerializer

    def retrieve(self, request, pk=None):
        """Return a specific Concern and its calculated value for the user's location."""

        location = request.user.userlocation_set.all()[0]
        concern = Concern.objects.get(id=pk)
        payload = ConcernSerializer(concern).data
        payload['value'] = concern.calculate_value(location)
        return Response(payload)
