from rest_framework.viewsets import ReadOnlyModelViewSet
from rest_framework.response import Response

from planit_data.models import Concern
from planit_data.serializers import ConcernSerializer


class ConcernViewSet(ReadOnlyModelViewSet):
    """Filter out the dummy scenario generated by migrations as a placeholder for older data."""

    queryset = Concern.objects.all()
    serializer_class = ConcernSerializer

    def retrieve(self, request, pk=None):
        """Return details of specific indicator if found."""
        concern = Concern.objects.get(id=pk)

        payload = concern.to_dict()
        location = request.user.location_set.latest()
        payload['value'] = concern.calculate_value(location, 1995, 2055)
        return Response(payload)
