# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('action_steps', '0001_add_collaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.CharField(default='icon-circle-empty', help_text='CSS icon class to apply to HTML elements that describe this category', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
    ]
