# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_steps', '0003_add_action_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actioncategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='actiontype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='collaborator',
            options={'ordering': ['name']},
        ),
    ]
