# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_steps', '0004_order_by_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actioncategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'action categories'},
        ),
    ]
