#!/bin/bash

set -e

if [[ -n "${PLANIT_DEBUG}" ]]; then
    set -x
fi

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Publish container images to Elastic Container Registry (ECR).
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        if [[ -n "${PLANIT_AWS_ECR_ENDPOINT}" ]]; then
            # Evaluate the return value of the get-login subcommand, which
            # is a docker login command with temporarily ECR credentials.
            eval "$(aws ecr get-login --no-include-email)"

            docker tag "planit-app:${GIT_COMMIT}" \
                   "${PLANIT_AWS_ECR_ENDPOINT}/planit-app:${GIT_COMMIT}"

            docker tag "planit-nginx:${GIT_COMMIT}" \
                   "${PLANIT_AWS_ECR_ENDPOINT}/planit-nginx:${GIT_COMMIT}"

            docker push "${PLANIT_AWS_ECR_ENDPOINT}/planit-app:${GIT_COMMIT}"
            docker push "${PLANIT_AWS_ECR_ENDPOINT}/planit-nginx:${GIT_COMMIT}"
        else
            echo "ERROR: No PLANIT_AWS_ECR_ENDPOINT variable defined."
            exit 1
        fi
    fi
fi
