#!/bin/bash

set -e

if [[ -n "${PLANIT_DEBUG}" ]]; then
    set -x
fi

set -u

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0") COMMAND OPTION[S]
Execute Terraform subcommands with remote state management.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        TERRAFORM_DIR="${DIR}/../deployment/terraform"
        echo
        echo "Attempting to deploy application version [${GIT_COMMIT}]..."
        echo "-----------------------------------------------------"
        echo
    fi

    if [[ -n "${PLANIT_SETTINGS_BUCKET}" ]]; then
        pushd "${TERRAFORM_DIR}"

        aws s3 cp "s3://${PLANIT_SETTINGS_BUCKET}/terraform/planit/terraform.tfvars" "${PLANIT_SETTINGS_BUCKET}.tfvars"

        case "${1}" in
            plan)
                rm -rf .terraform terraform.tfstate*
                terraform init \
                          -backend-config="bucket=${PLANIT_SETTINGS_BUCKET}" \
                          -backend-config="key=terraform/planit/state"

                terraform plan \
                          -var-file="${PLANIT_SETTINGS_BUCKET}.tfvars" \
                          -var="git_commit=\"${GIT_COMMIT}\"" \
                          -out="${PLANIT_SETTINGS_BUCKET}.tfplan"
                ;;
            apply)
                terraform apply "${PLANIT_SETTINGS_BUCKET}.tfplan"
                ;;
            *)
                echo "ERROR: I don't have support for that Terraform subcommand!"
                exit 1
                ;;
        esac

        popd
    else
        echo "ERROR: No PLANIT_SETTINGS_BUCKET variable defined."
        exit 1
    fi
fi
