#!/bin/bash

set -e

if [[ -n "${PLANIT_DEBUG}" ]]; then
	set -x
fi

function usage() {
	echo -n \
		 "Usage: $(basename "$0")

Starts servers using docker-compose.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
	if [ "${1:-}" = "--help" ]
	then
		usage
	elif [ "${1:-}" = "--angular" ]
	then
		docker-compose -f docker-compose.yml up django angular
	else		
		docker-compose -f docker-compose.yml up nginx django
	fi
fi
