#!/bin/bash

set -e

if [[ -n "${PLANIT_DEBUG}" ]]; then
	set -x
fi

function usage() {
	echo -n \
		 "Usage: $(basename "$0")

Starts servers using docker-compose.

Starts Django and the Angular development server (ng serve).

Use the --nginx flag to serve the AoT Production Angular bundle from nginx
instead of using 'ng serve'
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
	if [ "${1:-}" = "--help" ]
	then
		usage
	elif [ "${1:-}" = "--nginx" ]
	then
		docker-compose -f docker-compose.yml up nginx django
	else
		docker-compose -f docker-compose.yml up django angular
	fi
fi
