# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlocation_userrisk'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='planituser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='planituser',
            name='username',
        ),
        migrations.AlterField(
            model_name='planituser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='planituser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
