# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170922_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='planituser',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='planituser',
            name='organization',
            field=models.CharField(blank=True, max_length=150, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='planituser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='planituser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
