# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170922_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrisk',
            name='community_system',
        ),
        migrations.RemoveField(
            model_name='userrisk',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='userrisk',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userrisk',
            name='weather_event',
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
        migrations.DeleteModel(
            name='UserRisk',
        ),
    ]
