# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_move_user_risk_user_location_to_planitdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planituser',
            name='city',
        ),
        migrations.AddField(
            model_name='planituser',
            name='api_city_id',
            field=models.IntegerField(null=True),
        ),
    ]
