# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_default_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planituser',
            name='organizations',
            field=models.ManyToManyField(related_name='user_organizations', to='users.PlanItOrganization'),
        ),
    ]
