# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171108_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanItLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('api_city_id', models.IntegerField(null=True, unique=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
