# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_planitlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planitorganization',
            name='api_city_id',
        ),
        migrations.AddField(
            model_name='planitorganization',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.PlanItLocation'),
        ),
    ]
