# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171114_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitlocation',
            name='api_city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
