# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0011_auto_20171117_1413'),
        ('users', '0013_planituser_primary_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitorganization',
            name='weather_events',
            field=models.ManyToManyField(to='planit_data.WeatherEventRank'),
        ),
    ]
