# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_planitlocation_is_coastal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planituser',
            name='primary_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.PlanItOrganization'),
        ),
    ]
