# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180115_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitorganization',
            name='plan_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
