# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_planitorganization_plan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitorganization',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
