# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_planitorganization_created_by'),
        ('planit_data', '0023_migrate_wxeventrank_to_orgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planitorganization',
            name='weather_events',
        ),
    ]
