# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_planitlocation_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitorganization',
            name='plan_hyperlink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='planitorganization',
            name='plan_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
