# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_org_weather_events'),
        ('users', '0020_planitlocation_admin'),
    ]

    operations = [
    ]
