# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_planitorganization_addtl_plan_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitorganization',
            name='subscription',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('custom', 'Custom')], default='free_trial', max_length=16),
        ),
    ]
