# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_add_org_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitorganization',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
