# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 20:51
from __future__ import unicode_literals

from datetime import timedelta

from django.db import migrations
from django.utils import timezone

# This was the value of PlanItOrganization.DEFAULT_FREE_TRIAL_DAYS when this migration was written
DEFAULT_FREE_TRIAL_DAYS = 15
# This was the value of PlanItOrganization.Subscription.FREE_TRIAL when this migration was written
FREE_TRIAL = 'free_trial'


def set_org_subscription_end_date(apps, schema_editor):
    Organization = apps.get_model('users', 'PlanItOrganization')
    for org in Organization.objects.all():
        if org.subscription == FREE_TRIAL and org.subscription_end_date is None:
            trial_start = org.created_at or timezone.now()
            trial_end = trial_start + timedelta(days=DEFAULT_FREE_TRIAL_DAYS + 1)
            trial_end_rounded = trial_end.replace(hour=7, minute=0, second=0, microsecond=0)
            org.subscription_end_date = trial_end_rounded
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_add_field_subscriptionenddate'),
    ]

    operations = [
        migrations.RunPython(set_org_subscription_end_date, migrations.RunPython.noop)
    ]
