# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20180220_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitorganization',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='planitorganization',
            unique_together=set([('name', 'location')]),
        ),
    ]
