# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0028_merge_20180216_2338'),
        ('users', '0028_auto_20180223_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitorganization',
            name='community_systems',
            field=models.ManyToManyField(blank=True, related_name='community_systems', to='planit_data.CommunitySystem'),
        ),
    ]
