# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_planitorganization_community_systems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planitlocation',
            options={'verbose_name': 'location'},
        ),
        migrations.AlterModelOptions(
            name='planitorganization',
            options={'verbose_name': 'organization'},
        ),
    ]
