# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20180227_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitorganization',
            name='subscription',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('basic', 'Basic'), ('review', 'Review'), ('insights', 'Insights'), ('guidance', 'Guidance'), ('hourly', 'Pay as you go'), ('custom', 'Custom')], default='free_trial', max_length=16),
        ),
    ]
