# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20180228_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitorganization',
            name='plan_setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
