# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_org_subscription_add_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitorganization',
            name='subscription_pending',
            field=models.BooleanField(default=False),
        ),
    ]
