# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_add_org_subscription_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planituser',
            name='organizations',
            field=models.ManyToManyField(related_name='users', to='users.PlanItOrganization'),
        ),
    ]
