# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20180306_1904'),
        ('users', '0034_planitorganization_plan_setup_complete'),
    ]

    operations = [
    ]
