# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 19:45
from __future__ import unicode_literals
from itertools import groupby

from django.db import migrations


def align_org_weather_events(apps, schema_editor):
        """Populate the organization weather events from associated risks"""
        OrganizationWeatherEvent = apps.get_model('planit_data', 'OrganizationWeatherEvent')
        OrganizationRisk = apps.get_model('planit_data', 'OrganizationRisk')

        OrganizationWeatherEvent.objects.all().delete()

        all_risks = (OrganizationRisk.objects.filter(
                        weather_event__isnull=False
                     ).values('organization_id', 'weather_event_id')
                      .order_by('organization_id').distinct())
        for organization_id, org_risks in groupby(all_risks, lambda r: r['organization_id']):
            OrganizationWeatherEvent.objects.bulk_create(
                OrganizationWeatherEvent(
                    weather_event_id=risk['weather_event_id'],
                    organization_id=organization_id,
                    order=index)
                for index, risk in enumerate(org_risks, 1)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_merge_20180307_1421'),
    ]

    operations = [
        migrations.RunPython(align_org_weather_events, migrations.RunPython.noop)
    ]
