# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_add_city_profile_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityprofile',
            name='about_adaptation_status',
            field=models.CharField(blank=True, choices=[('exists', 'Currently exists'), ('inprogress', 'In progress'), ('doesnotexist', 'Does not exist, but intend to undertake'), ('noplanstoundertake', 'Does not exist, no plans to undertake'), ('donotknow', 'Do not know')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='cityprofile',
            name='about_commitment_status',
            field=models.CharField(blank=True, choices=[('exists', 'Currently exists'), ('inprogress', 'In progress'), ('doesnotexist', 'Does not exist, but intend to undertake'), ('noplanstoundertake', 'Does not exist, no plans to undertake'), ('donotknow', 'Do not know')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='cityprofile',
            name='about_economic_sector',
            field=models.CharField(blank=True, choices=[('Mining', 'Mining'), ('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Utilities', 'Utilities'), ('Wholesale trade', 'Wholesale trade'), ('Retail trade', 'Retail trade'), ('Transportation and warehousing', 'Transportation and warehousing'), ('Information', 'Information'), ('Financial activities', 'Financial activities'), ('Professional and business services', 'Professional and business services'), ('Educational services', 'Educational services'), ('Healthcare and social assistance', 'Healthcare and social assistance'), ('Leisure and hospitality', 'Leisure and hospitality'), ('Agriculture', 'Agriculture'), ('Forestry', 'Forestry'), ('Fishing and hunting', 'Fishing and hunting'), ('Other', 'Other')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='cityprofile',
            name='about_mitigation_status',
            field=models.CharField(blank=True, choices=[('exists', 'Currently exists'), ('inprogress', 'In progress'), ('doesnotexist', 'Does not exist, but intend to undertake'), ('noplanstoundertake', 'Does not exist, no plans to undertake'), ('donotknow', 'Do not know')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='cityprofile',
            name='about_operational_budget_usd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cityprofile',
            name='action_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('notyet', 'Not yet'), ('inprogress', "It's in progress"), ('donotknow', "I don't know")], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='cityprofile',
            name='assessment_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('notyet', 'Not yet'), ('inprogress', "It's in progress"), ('donotknow', "I don't know")], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='cityprofile',
            name='plan_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('notyet', 'Not yet'), ('inprogress', "It's in progress"), ('donotknow', "I don't know")], default='', max_length=128),
        ),
    ]
