# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_add_city_profile_about_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planituser',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.PlanItOrganization'),
        ),
    ]
