# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 16:14
from __future__ import unicode_literals

from django.db import migrations


def hourly_to_custom(apps, schema_editor):
    PlanItOrganization = apps.get_model('users', 'PlanItOrganization')

    PlanItOrganization.objects.filter(subscription='hourly').update(subscription='custom')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20180330_1859'),
    ]

    operations = [
        migrations.RunPython(hourly_to_custom, migrations.RunPython.noop)
    ]
