# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20180330_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityprofile',
            name='assessment_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'Not yet'), ('donotknow', 'I don’t know')], default='', max_length=128),
        ),
    ]
