# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit_data', '0038_auto_20180327_1923'),
        ('users', '0044_merge_20180403_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitlocation',
            name='georegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planit_data.GeoRegion'),
        ),
    ]
