# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 18:38
from __future__ import unicode_literals

from django.db import migrations


def set_default_subscription_end_notified(apps, schema_editor):
        PlanItOrganization = apps.get_model('users', 'PlanItOrganization')

        PlanItOrganization.objects.all().update(
            subscription_end_notified=False
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_planitorganization_subscription_end_notified_default_false'),
    ]

    operations = [
        migrations.RunPython(set_default_subscription_end_notified, migrations.RunPython.noop)
    ]
