# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_planituser_trial_end_notified_no_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitorganization',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
