# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_planitorganization_subscription_end_date_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planituser',
            name='trial_end_notified',
            field=models.BooleanField(default=False, help_text='Indicates if the user has been notified about an upcoming trial expiration'),
        ),
    ]
