# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-27 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_set_datasets_on_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='planituser',
            name='can_create_multiple_organizations',
            field=models.BooleanField(default=False, help_text='Designates whether user can create multiple organizations.'),
        ),
    ]
