# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_planituser_can_create_multiple_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitorganization',
            name='source',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('missy_importer', 'Missy Importer')], max_length=16, null=True),
        ),
    ]
