# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 17:14
from __future__ import unicode_literals

from django.db import migrations


def set_planitorganization_source_initial_values(apps, schema_editor):

    Organization = apps.get_model('users', 'PlanItOrganization')

    # Move org association with missy importer to source field
    # Before this migration, an implicit relationship existed that any org with
    # location.api_city_id == None was created by the importer.
    for org in Organization.objects.all():
        if org.location.api_city_id is None:
            org.source = 'missy_importer'
        else:
            org.source = 'user'
        org.save()


def revert_planitorganization_source(apps, schema_editor):
    Organization = apps.get_model('users', 'PlanItOrganization')

    # All we know is that we can re-create the previous assumption, which is that any org
    # with a missy importer source can have its planitlocation.api_city_id set to None
    for org in Organization.objects.filter(source='missy_importer'):
        org.location.api_city_id = None
        org.location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_add_planitorganization_source'),
    ]

    operations = [
        migrations.RunPython(set_planitorganization_source_initial_values,
                             revert_planitorganization_source)
    ]
