# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_set_planitorganization_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitorganization',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('missy_importer', 'Missy Importer')], default='user', max_length=16),
        ),
    ]
