# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_update_planitorganization_source_notnull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planitlocation',
            name='api_city_id',
        ),
    ]
