# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_remove_planitlocation_api_city_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='planituser',
            name='removed_organizations',
            field=models.ManyToManyField(blank=True, related_name='former_users', to='users.PlanItOrganization'),
        ),
    ]
