# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_planituser_removed_organizations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planitlocation',
            unique_together=set([('name', 'admin', 'point')]),
        ),
    ]
