# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 18:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20190418_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitorganization',
            name='bounds',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
