# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_planitorganization_bounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitorganization',
            name='creator_location_admin',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='planitorganization',
            name='creator_location_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
