# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-03 14:12
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20191105_1831'),
    ]

    operations = [
        CITextExtension()
    ]
