# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-03 14:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_check_user_email_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planituser',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
